### ISSUE TITLE
Engine should use the solutions repo

### ISSUE THREAD

**Issue by basimr** [project-lovelace/lovelace-problems#21]
Instead of using solve_test_case(test_case) the engine should load the correct solution/function from the lovelace-solutions repo. This way we don’t repeat the solution code.

**Comment by ali-ramadhan** [comment]
Should note that because the solution files use dashes in the filenames (e.g. `rocket-science.py`) importing the solutions is awkward and we have to use `__import__` like:

```python
_m = __import__('solutions.rocket-science', globals(), locals(), fromlist=['rocket_fuel'], level=0)
_m.rocket_fuel(45)
```

I think we need the dashes so that the solution filename matches the "problem name" in Django, but if not, would be nice to switch back to dashes.

X-ref: https://github.com/project-lovelace/lovelace-website/issues/38

**Comment by ali-ramadhan** [comment]
Never mind, `importlib.import_module('solutions.rocket-science')` works in the REPL but not in production. I also don't fully understand python relative imports.
